config/routes.rb
Myapps::Application.routes.draw do
  resources :products
	resources :adminusers
  resources :login
  resources :users
  resources :fuckforms

	get "products/buy/"
  get "home/index"
  get "users/index"
  get "login/index"
  post "login/index"
  get "login/logout"
  get "adminusers/index"
  get "products/index"
  
  resources :posts do
  resources :comments
end

     match 'products/buy/:id' => 'products#buy'







   root :to => 'home#index'


end

app/models/adminuser.rb
require "digest"

class Adminuser < ActiveRecord::Base
	has_many :user
	validates_presence_of :password
	validates_presence_of :username
	validates_presence_of :fullname
	validates :email, :presence => true, :email => true
	before_save :hash_password
	# Setup the salt value and hash the password before we save everything to the
  # database.
  def hash_password
       self.password = Digest::MD5.hexdigest(self.password)
  end
  
 
  def password_matches?(password_to_match)
		self.password == Digest::MD5.hexdigest(password_to_match)
  end
 
  
end

app/controllers/adminuser_controller.rb
class AdminuserController < ApplicationController
  def login
  end
end

app/controllers/adminusers_controller.rb
class AdminusersController < ApplicationController
	
	before_filter :login_required
	#skip_before_filter :login_required
  def login
	
   if request.post? and params[:username]
    @user = Adminuser.new(params[:adminuser])
 
    user = Adminuser.find_by_username(params[:username])
	
    # If we found a user with that username and the password provided matches
    # the password on file for that user, we can login the user.
    if user and user.password_matches?(params[:password])
      session[:user_id] = user.id
      #user.last_login = Time.now
      #user.save
 
      if user.id?
        redirect_to adminusers_path
      else
        redirect_to adminusers_path + '/login'
      end
    else
      flash[:notice] = "Sorry, no user was found with that username/password combination."
    end
	
   end
   
    
  end
    # GET /adminusers
  # GET /adminusers.json
  def index
    @adminusers = Adminuser.all
	@users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @adminusers }
    end
  end

  # GET /adminusers/1
  # GET /adminusers/1.json
  def show
    @adminuser = Adminuser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @adminuser }
    end
  end

  # GET /adminusers/new
  # GET /adminusers/new.json
  def new
    @adminuser = Adminuser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @adminuser }
    end
  end

  # GET /adminusers/1/edit
  def edit
    @adminuser = Adminuser.find(params[:id])
  end

  # POST /adminusers
  # POST /adminusers.json
  def create
    @adminuser = Adminuser.new(params[:adminuser])

    respond_to do |format|
      if @adminuser.save
        format.html { redirect_to @adminuser, notice: 'Adminuser was successfully created.' }
        format.json { render json: @adminuser, status: :created, location: @adminuser }
      else
        format.html { render action: "new" }
        format.json { render json: @adminuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /adminusers/1
  # PUT /adminusers/1.json
  def update
    @adminuser = Adminuser.find(params[:id])

    respond_to do |format|
      if @adminuser.update_attributes(params[:adminuser])
        format.html { redirect_to @adminuser, notice: 'Adminuser was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @adminuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adminusers/1
  # DELETE /adminusers/1.json
  def destroy
    @adminuser = Adminuser.find(params[:id])
    @adminuser.destroy

    respond_to do |format|
      format.html { redirect_to adminusers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/adminuser_helper.rb
module AdminuserHelper
end

app/views/adminusers/_form.html.erb
<%= form_for(@adminuser) do |f| %>
  <% if @adminuser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adminuser.errors.count, "error") %> prohibited this adminuser from being saved:</h2>

      <ul>
      <% @adminuser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :fullname %><br />
    <%= f.text_field :fullname %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adminusers/index.html.erb
<%= content_for :menu do %>
<ul>
	<li><%= link_to "Home", "/" %></li>
	<li><a href="#">News</a></li>
	<li><a href="#">About Us</a></li>
	<li><a href="#">Contact Us</a></li>
</ul>
<% end %>
<h1>Listing adminusers</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Fullname</th>
    <th>Address</th>
    <th>Age</th>
	<th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @adminusers.each do |adminuser| %>
  <tr>
    <td><%= adminuser.username %></td>
    <td><%= adminuser.email %></td>
    <td><%= adminuser.fullname %></td>
    <td><%= adminuser.address %></td>
    <td><%= adminuser.age %></td>
	<td><%= adminuser.password %></td>
    <td><%= link_to 'Show', adminuser %></td>
    <td><%= link_to 'Edit', edit_adminuser_path(adminuser) %></td>
    <td><%= link_to 'Destroy', adminuser, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Adminuser', new_adminuser_path %>

app/views/adminusers/login.html.erb
<% if flash[:notice] %>
  <%= h flash[:notice] %>
<% end %>
<%= form_tag :action => 'login' do%>

  <%= label_tag :username, "Username: " %><br>
  <%= text_field_tag :username %><br>

  <%= label_tag :password, "Password:" %><br>
  <%= password_field_tag :password %><br>

  <%= submit_tag "Login" %>

<% end %>