config/routes.rb
Myapps::Application.routes.draw do
  resources :products
	resources :adminusers
  resources :login
  resources :users
  resources :fuckforms

	get "products/buy/"
  get "home/index"
  get "users/index"
  get "login/index"
  post "login/index"
  get "login/logout"
  get "adminusers/index"
  get "products/index"
  
  resources :posts do
  resources :comments
end

     match 'products/buy/:id' => 'products#buy'







   root :to => 'home#index'


end

app/controllers/fuckforms_controller.rb
class FuckformsController < ApplicationController
  # GET /fuckforms
  # GET /fuckforms.json
  def index
    @fuckforms = Fuckform.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fuckforms }
    end
  end

  # GET /fuckforms/1
  # GET /fuckforms/1.json
  def show
    @fuckform = Fuckform.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fuckform }
    end
  end

  # GET /fuckforms/new
  # GET /fuckforms/new.json
  def new
    @fuckform = Fuckform.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fuckform }
    end
  end

  # GET /fuckforms/1/edit
  def edit
    @fuckform = Fuckform.find(params[:id])
  end

  # POST /fuckforms
  # POST /fuckforms.json
  def create
    @fuckform = Fuckform.new(params[:fuckform])

    respond_to do |format|
      if @fuckform.save
        format.html { redirect_to @fuckform, notice: 'Fuckform was successfully created.' }
        format.json { render json: @fuckform, status: :created, location: @fuckform }
      else
        format.html { render action: "new" }
        format.json { render json: @fuckform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fuckforms/1
  # PUT /fuckforms/1.json
  def update
    @fuckform = Fuckform.find(params[:id])

    respond_to do |format|
      if @fuckform.update_attributes(params[:fuckform])
        format.html { redirect_to @fuckform, notice: 'Fuckform was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fuckform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fuckforms/1
  # DELETE /fuckforms/1.json
  def destroy
    @fuckform = Fuckform.find(params[:id])
    @fuckform.destroy

    respond_to do |format|
      format.html { redirect_to fuckforms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fuckforms_helper.rb
module FuckformsHelper
end

app/views/fuckforms/_form.html.erb
<%= form_for(@fuckform) do |f| %>
  <% if @fuckform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fuckform.errors.count, "error") %> prohibited this fuckform from being saved:</h2>

      <ul>
      <% @fuckform.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fuckforms/edit.html.erb
<h1>Editing fuckform</h1>

<%= render 'form' %>

<%= link_to 'Show', @fuckform %> |
<%= link_to 'Back', fuckforms_path %>

app/views/fuckforms/index.html.erb
<h1>Listing fuckforms</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fuckforms.each do |fuckform| %>
  <tr>
    <td><%= link_to 'Show', fuckform %></td>
    <td><%= link_to 'Edit', edit_fuckform_path(fuckform) %></td>
    <td><%= link_to 'Destroy', fuckform, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fuckform', new_fuckform_path %>

app/views/fuckforms/new.html.erb
<h1>New fuckform</h1>

<%= render 'form' %>

<%= link_to 'Back', fuckforms_path %>

app/views/fuckforms/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_fuckform_path(@fuckform) %> |
<%= link_to 'Back', fuckforms_path %>